DROP DATABASE IF EXISTS carsdb;
CREATE DATABASE carsdb;
USE carsdb;
CREATE TABLE cars (
  id INT AUTO_INCREMENT PRIMARY KEY,
  year INT NOT NULL,
  color VARCHAR(255) NOT NULL,
  manufacturer VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

